### ISSUE TITLE
Linking error with MinGW 4.8.2

### ISSUE THREAD

**Issue by drizt** [kuba--/zip#56]
Here I just copied my question from [StackOverflow](https://stackoverflow.com/questions/51914879/how-to-link-against-inline-functions-in-mingw-gcc).

I need to compile some library (kuba zip) with MinGW 4.8.2. I got linking error.

    [2/2 12.0/sec] Linking C executable test\test.exe.exe
    FAILED: test/test.exe.exe 
    cmd.exe /C "cd . && C:\mingw32\bin\gcc.exe  -std=c99 -Wall -Wextra -pedantic -g   test/CMakeFiles/test.exe.dir/test.c.obj test/CMakeFiles/test.exe.dir/__/src/zip.c.obj  -o test\test.exe.exe -Wl,--out-implib,test\libtest.exe.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
    test/CMakeFiles/test.exe.dir/__/src/zip.c.obj: In function `zip_entry_close':
    C:\msys64\home\ivan\dev\zip\debug-qt4/../src/zip.c:440: undefined reference to `localtime_s'

Here problem in `localtime_s` function. `localtime_s` is declared as `inline` and must be inlined. But by fact it is not happens.

`localtime_s` declaration.

    __CRT_INLINE errno_t __cdecl localtime_s(struct tm *_Tm,const time_t *_Time) { return _localtime32_s(_Tm,_Time); }

I wrote some testcase for this.

    #include <time.h>
    int main()
    {
        struct tm _Tm;
        time_t _Time;
        localtime_s(&_Tm, &_Time);
        return 0;
    }

With gcc it produces link error:

    $ gcc localtime_test.c
    C:\msys64\tmp\ccEMjUQ8.o:localtime_test.c:(.text+0x1e): undefined reference to `localtime_s'
    collect2.exe: error: ld returned 1 exit status

But no error with g++ or MinGW 5.3.0 (both gcc and g++). So how to make my testcase working with MinGW 4.8.2 gcc?

I know that I can just use _localtime32_s in my case and it will work. But this seems some incorrect decision.

**Comment by kuba--** [comment]
What if we add following flags to MSYS2 compilation:
```
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT=1")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /D _CRT_NONSTDC_NO_WARNINGS=1 /D _CRT_SECURE_NO_WARNINGS=1")
```

Will that work for you?
